2021-09-30 09:46:24,370: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 2556, 140295323637568, Watching for file changes with StatReloader
2021-09-30 09:47:28,064: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-9.jpg
2021-09-30 09:47:28,078: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295206201088, Not Found: /dist/images/profile-11.jpg
2021-09-30 09:47:28,096: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/profile-12.jpg
2021-09-30 09:47:28,144: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-2.jpg
2021-09-30 09:47:28,269: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/profile-14.jpg
2021-09-30 09:47:28,338: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/profile-2.jpg
2021-09-30 09:47:28,342: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-6.jpg
2021-09-30 09:47:28,349: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295206201088, Not Found: /dist/images/preview-11.jpg
2021-09-30 09:47:28,457: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295188367104, Not Found: /dist/images/preview-13.jpg
2021-09-30 09:47:28,479: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-9.jpg
2021-09-30 09:47:28,768: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/preview-5.jpg
2021-09-30 09:47:28,854: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-15.jpg
2021-09-30 09:47:28,940: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/preview-1.jpg
2021-09-30 09:47:28,975: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295188367104, Not Found: /dist/images/preview-3.jpg
2021-09-30 09:47:29,005: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294972503808, Not Found: /dist/images/preview-8.jpg
2021-09-30 09:47:29,136: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294964111104, Not Found: /dist/images/preview-12.jpg
2021-09-30 09:47:29,161: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140294955718400, Not Found: /dist/images/profile-3.jpg
2021-09-30 09:47:29,186: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/images/profile-4.jpg
2021-09-30 09:47:30,104: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /dist/json/location.json
2021-09-30 09:47:30,184: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 2556, 140295197284096, Getting Clients Page...
2021-09-30 09:47:30,785: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:39,725: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 2556, 140295197284096, Getting Adversaires page.
2021-09-30 09:47:39,966: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:42,626: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 2556, 140295197284096, Getting Clients Page...
2021-09-30 09:47:42,868: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:47:45,798: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/dist/images/profile-9.jpg
2021-09-30 09:48:05,004: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:48:07,027: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/dist/images/profile-9.jpg
2021-09-30 09:49:17,291: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:27,205: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 2556, 140295197284096, Getting Clients Page...
2021-09-30 09:49:27,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:33,340: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 2556, 140295197284096, Getting Adversaires page.
2021-09-30 09:49:33,570: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:49:35,169: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/dist/images/profile-9.jpg
2021-09-30 09:50:59,391: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 09:53:15,416: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:21,677: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 2556, 140295197284096, Getting Adversaires page.
2021-09-30 10:02:22,175: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:42,631: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 2556, 140295197284096, Getting Adversaires page.
2021-09-30 10:02:42,987: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 10:02:57,137: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 2556, 140295197284096, Getting Clients Page...
2021-09-30 10:02:57,387: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 2556, 140295197284096, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:07:38,996: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5206, 139808560310080, Watching for file changes with StatReloader
2021-09-30 15:08:41,888: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:08:41,890: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808366130944, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:08:41,898: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:08:41,905: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:08:41,959: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808340952832, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:08:42,182: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:08:42,415: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:08:42,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:08:42,474: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:08:42,483: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:08:42,511: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:08:42,518: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:08:42,589: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:08:42,694: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:08:42,758: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808332560128, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:08:42,778: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808357738240, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:08:42,786: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808442873600, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:08:42,941: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:08:43,889: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /dist/json/location.json
2021-09-30 15:08:45,566: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 5206, 139808349345536, Getting Clients Page...
2021-09-30 15:08:45,968: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:09:08,411: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 5206, 139808349345536, Getting Adversaires page.
2021-09-30 15:09:08,830: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:12:03,952: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 5206, 139808349345536, Getting Adversaires page.
2021-09-30 15:12:04,345: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5206, 139808349345536, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:12:57,542: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5206, 139808560310080, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/models.py changed, reloading.
2021-09-30 15:12:59,212: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5414, 140288358336320, Watching for file changes with StatReloader
2021-09-30 15:19:21,214: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5414, 140288240899840, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:20:39,298: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5414, 140288358336320, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:20:40,686: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5541, 140561659561792, Watching for file changes with StatReloader
2021-09-30 15:24:00,746: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5541, 140561659561792, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:24:02,240: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5557, 140537614763840, Watching for file changes with StatReloader
2021-09-30 15:24:55,480: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5557, 140537614763840, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:24:57,461: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5564, 140561463936832, Watching for file changes with StatReloader
2021-09-30 15:25:45,493: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5564, 140561463936832, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:25:46,775: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5581, 140370681247552, Watching for file changes with StatReloader
2021-09-30 15:25:56,116: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5581, 140370681247552, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:25:57,550: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5586, 140481411053376, Watching for file changes with StatReloader
2021-09-30 15:26:27,711: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5586, 140481411053376, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:26:29,023: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5605, 140375845934912, Watching for file changes with StatReloader
2021-09-30 15:26:55,540: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5605, 140375845934912, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/models.py changed, reloading.
2021-09-30 15:26:56,816: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5610, 139748853249856, Watching for file changes with StatReloader
2021-09-30 15:30:58,002: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5610, 139748853249856, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:30:59,171: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5663, 140339975173952, Watching for file changes with StatReloader
2021-09-30 15:31:22,788: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5663, 140339975173952, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:31:23,977: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5674, 140149504776000, Watching for file changes with StatReloader
2021-09-30 15:33:41,967: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5674, 140149504776000, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:33:43,169: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5714, 140118997686080, Watching for file changes with StatReloader
2021-09-30 15:34:43,234: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5714, 140118997686080, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:34:44,664: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5748, 140291903178560, Watching for file changes with StatReloader
2021-09-30 15:34:46,159: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5748, 140291903178560, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:34:47,362: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5752, 139726217234240, Watching for file changes with StatReloader
2021-09-30 15:37:33,581: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 5752, 139726099797760, Getting Adversaires page.
2021-09-30 15:37:33,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:37:37,263: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:37:37,766: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /favicon.ico
2021-09-30 15:39:27,934: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:39:27,995: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:39:28,028: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:39:28,057: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:39:28,123: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:39:28,131: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:39:28,177: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:39:28,207: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:39:28,245: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:39:28,262: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:39:28,277: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:39:28,332: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:39:28,482: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726022768384, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:39:28,601: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726099797760, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:39:28,849: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:39:28,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726005982976, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:39:28,957: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139725997590272, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:39:29,104: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:39:29,626: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5752, 139726014375680, Not Found: /dist/json/location.json
2021-09-30 15:39:36,300: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5858, 140106107283264, Watching for file changes with StatReloader
2021-09-30 15:39:37,833: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:39:37,847: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:39:37,913: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:39:38,025: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:39:38,033: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:39:38,166: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:39:38,373: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:39:38,425: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:39:38,626: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:39:38,647: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:39:38,712: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:39:38,829: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:39:38,841: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:39:38,898: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:39:38,915: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105905420032, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:39:39,059: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105923516160, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:39:39,067: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105888634624, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:39:39,116: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:39:39,935: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /dist/json/location.json
2021-09-30 15:39:40,020: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 5858, 140105914337024, Getting Adversaires page.
2021-09-30 15:39:40,338: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:39:42,714: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:40:37,434: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5858, 140105914337024, Internal Server Error: /adversaires/1/edit
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 125, in adversaire_form
    form = AdversaireForm(instance=adversaire)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py", line 14, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py", line 57, in __init__
    super(AdversaireForm, self).__init__(*args, **kwargs)
NameError: name 'AdversaireForm' is not defined
2021-09-30 15:41:19,368: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5858, 140106107283264, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:41:20,582: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5931, 140490179712832, Watching for file changes with StatReloader
2021-09-30 15:41:28,408: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/profile-9.jpg
2021-09-30 15:41:28,415: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/profile-11.jpg
2021-09-30 15:41:28,476: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489982469888, Not Found: /dist/images/profile-12.jpg
2021-09-30 15:41:28,491: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-5.jpg
2021-09-30 15:41:28,528: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/profile-2.jpg
2021-09-30 15:41:28,542: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/preview-2.jpg
2021-09-30 15:41:28,644: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/preview-1.jpg
2021-09-30 15:41:28,711: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-15.jpg
2021-09-30 15:41:28,733: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/preview-9.jpg
2021-09-30 15:41:28,781: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/preview-8.jpg
2021-09-30 15:41:28,940: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-3.jpg
2021-09-30 15:41:29,094: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489965684480, Not Found: /dist/images/preview-13.jpg
2021-09-30 15:41:29,140: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/profile-14.jpg
2021-09-30 15:41:29,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489974077184, Not Found: /dist/images/profile-6.jpg
2021-09-30 15:41:29,286: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/preview-11.jpg
2021-09-30 15:41:29,298: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/preview-12.jpg
2021-09-30 15:41:29,526: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /dist/images/profile-3.jpg
2021-09-30 15:41:29,749: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/images/profile-4.jpg
2021-09-30 15:41:30,473: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489990862592, Not Found: /dist/json/location.json
2021-09-30 15:41:45,595: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 5931, 140489990862592, Getting Adversaires page.
2021-09-30 15:41:46,619: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:41:50,060: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:42:02,600: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:42:20,196: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5931, 140489957291776, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:06,085: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5931, 140490179712832, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:43:07,455: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5987, 140587671586624, Watching for file changes with StatReloader
2021-09-30 15:43:23,337: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5987, 140587671586624, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:43:24,856: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 5993, 139965050394432, Watching for file changes with StatReloader
2021-09-30 15:43:43,912: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:45,121: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:43:49,700: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 5993, 139964838823680, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:44:36,225: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 5993, 139965050394432, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:44:37,650: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6030, 140548610438976, Watching for file changes with StatReloader
2021-09-30 15:45:26,136: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6030, 140548610438976, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/forms.py changed, reloading.
2021-09-30 15:45:27,822: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6040, 140184845453120, Watching for file changes with StatReloader
2021-09-30 15:45:30,916: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6040, 140184727754496, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 15:45:36,425: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6040, 140184645531392, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 15:45:57,807: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6040, 140184845453120, /home/kali/Projects/Python_Projects/justice_law_office_django/parents/parent.py changed, reloading.
2021-09-30 15:45:59,060: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6070, 140361679939392, Watching for file changes with StatReloader
2021-09-30 16:01:39,937: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6070, 140361679939392, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/forms.py changed, reloading.
2021-09-30 16:01:41,225: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6199, 139634260596544, Watching for file changes with StatReloader
2021-09-30 16:01:59,291: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6199, 139634260596544, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/forms.py changed, reloading.
2021-09-30 16:02:00,791: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6216, 140064488326976, Watching for file changes with StatReloader
2021-09-30 16:02:14,396: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6216, 140064488326976, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/forms.py changed, reloading.
2021-09-30 16:02:15,825: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6225, 140068990011200, Watching for file changes with StatReloader
2021-09-30 16:02:35,092: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6225, 140068990011200, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/forms.py changed, reloading.
2021-09-30 16:02:36,349: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6231, 140133180000064, Watching for file changes with StatReloader
2021-09-30 16:02:46,941: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 6231, 140133062563584, Getting Clients Page...
2021-09-30 16:02:47,394: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:02:51,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/2/dist/images/profile-9.jpg
2021-09-30 16:03:16,423: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:03:19,781: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/2/dist/images/profile-9.jpg
2021-09-30 16:03:28,737: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:17:52,151: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires_all:46], adversaires.views, views, 6231, 140133062563584, Getting Adversaires page.
2021-09-30 16:17:52,468: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:17:58,459: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 6231, 140133062563584, Getting Clients Page...
2021-09-30 16:17:58,683: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6231, 140133062563584, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:22:56,921: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6231, 140133180000064, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:22:58,104: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6422, 139787773675328, Watching for file changes with StatReloader
2021-09-30 16:27:47,246: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6422, 139787773675328, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:27:48,466: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6503, 139987804284736, Watching for file changes with StatReloader
2021-09-30 16:30:55,829: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6503, 139987804284736, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:30:57,014: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6552, 140669490079552, Watching for file changes with StatReloader
2021-09-30 16:35:59,864: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6552, 140669490079552, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:36:01,135: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6606, 140269694027584, Watching for file changes with StatReloader
2021-09-30 16:39:18,173: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6606, 140269694027584, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:39:19,471: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6667, 140619062851392, Watching for file changes with StatReloader
2021-09-30 16:46:56,187: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6667, 140619062851392, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:46:57,413: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6735, 139908392421184, Watching for file changes with StatReloader
2021-09-30 16:48:02,514: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6735, 139908392421184, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:48:03,743: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6744, 139629614331712, Watching for file changes with StatReloader
2021-09-30 16:48:09,627: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6744, 139629614331712, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:48:10,835: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6749, 140104089560896, Watching for file changes with StatReloader
2021-09-30 16:48:30,970: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6749, 140104089560896, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:48:32,275: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6755, 140074410100544, Watching for file changes with StatReloader
2021-09-30 16:48:46,907: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6765, 140001877104448, Watching for file changes with StatReloader
2021-09-30 16:49:24,470: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:49:32,473: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 6765, 140001759405824, Page list of 'Adversaires'.
2021-09-30 16:49:32,743: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:49:51,585: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: adversaire_form:175], adversaires.views, views, 6765, 140001759405824, Page Creating of 'Adversaire'
2021-09-30 16:49:51,983: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 16:50:13,162: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: adversaire_form:163], adversaires.views, views, 6765, 140001759405824, 'BOULAMIN Ahmed' Adversaire Updated.
2021-09-30 16:50:13,235: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 6765, 140001759405824, Page list of 'Adversaires'.
2021-09-30 16:50:13,491: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6765, 140001759405824, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:50:42,797: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6765, 140001877104448, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:50:44,174: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6821, 139661070862144, Watching for file changes with StatReloader
2021-09-30 16:51:37,764: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6821, 139661070862144, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:51:38,931: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6864, 140590770149184, Watching for file changes with StatReloader
2021-09-30 16:52:22,821: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6864, 140590770149184, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/forms.py changed, reloading.
2021-09-30 16:52:24,529: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6925, 140605988534080, Watching for file changes with StatReloader
2021-09-30 16:55:20,365: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6925, 140605988534080, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 16:55:21,643: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6967, 140692368156480, Watching for file changes with StatReloader
2021-09-30 16:55:42,022: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6967, 140692368156480, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py changed, reloading.
2021-09-30 16:55:43,994: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 6976, 140583466444608, Watching for file changes with StatReloader
2021-09-30 16:55:45,978: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 6976, 140583348745984, Page list of 'Adversaires'.
2021-09-30 16:55:46,373: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583348745984, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:56:07,327: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-9.jpg
2021-09-30 16:56:07,503: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-2.jpg
2021-09-30 16:56:07,583: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/profile-12.jpg
2021-09-30 16:56:07,595: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-11.jpg
2021-09-30 16:56:07,683: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-14.jpg
2021-09-30 16:56:07,809: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-11.jpg
2021-09-30 16:56:07,815: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-13.jpg
2021-09-30 16:56:07,913: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-6.jpg
2021-09-30 16:56:07,977: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-9.jpg
2021-09-30 16:56:07,987: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-2.jpg
2021-09-30 16:56:08,076: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-5.jpg
2021-09-30 16:56:08,150: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-15.jpg
2021-09-30 16:56:08,127: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/preview-1.jpg
2021-09-30 16:56:08,166: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583348745984, Not Found: /dist/images/preview-8.jpg
2021-09-30 16:56:08,303: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/preview-3.jpg
2021-09-30 16:56:08,347: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-12.jpg
2021-09-30 16:56:08,393: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-3.jpg
2021-09-30 16:56:08,413: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-4.jpg
2021-09-30 16:56:09,052: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/json/location.json
2021-09-30 16:56:09,807: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-9.jpg
2021-09-30 16:56:09,827: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/profile-2.jpg
2021-09-30 16:56:09,872: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-12.jpg
2021-09-30 16:56:09,897: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583246743296, Not Found: /dist/images/preview-5.jpg
2021-09-30 16:56:09,879: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/profile-11.jpg
2021-09-30 16:56:09,923: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-2.jpg
2021-09-30 16:56:10,135: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-15.jpg
2021-09-30 16:56:10,163: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-1.jpg
2021-09-30 16:56:10,175: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-9.jpg
2021-09-30 16:56:10,179: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/preview-8.jpg
2021-09-30 16:56:10,205: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583271921408, Not Found: /dist/images/profile-6.jpg
2021-09-30 16:56:10,243: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583246743296, Not Found: /dist/images/preview-11.jpg
2021-09-30 16:56:10,247: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/profile-14.jpg
2021-09-30 16:56:10,253: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/preview-13.jpg
2021-09-30 16:56:10,261: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583263528704, Not Found: /dist/images/preview-3.jpg
2021-09-30 16:56:10,351: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583238350592, Not Found: /dist/images/preview-12.jpg
2021-09-30 16:56:10,363: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583229957888, Not Found: /dist/images/profile-3.jpg
2021-09-30 16:56:10,417: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/images/profile-4.jpg
2021-09-30 16:56:11,117: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /dist/json/location.json
2021-09-30 16:56:12,608: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 6976, 140583255136000, Getting Clients Page...
2021-09-30 16:56:12,661: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 6976, 140583255136000, Page list of 'Clients'.
2021-09-30 16:56:12,918: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 16:56:44,596: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 6976, 140583255136000, Page list of 'Adversaires'.
2021-09-30 16:56:44,951: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 6976, 140583255136000, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:00:06,438: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 6976, 140583466444608, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 17:00:08,519: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7130, 139697041512256, Watching for file changes with StatReloader
2021-09-30 17:02:23,193: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7130, 139697041512256, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 17:02:24,665: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7168, 140253974193984, Watching for file changes with StatReloader
2021-09-30 17:02:46,085: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7168, 140253974193984, /home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py changed, reloading.
2021-09-30 17:02:47,663: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7184, 140445291833152, Watching for file changes with StatReloader
2021-09-30 17:03:39,242: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:03:39,409: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:03:39,732: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:03:47,537: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:03:47,616: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:03:47,812: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/Casablanca/search/dist/images/profile-9.jpg
2021-09-30 17:03:51,729: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:03:51,827: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:03:52,085: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:03:59,241: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:03:59,317: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:03:59,526: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:04:04,917: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:04:05,100: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:04:15,338: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:04:15,449: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:05:22,357: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:05:22,798: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:30,443: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:05:30,618: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:35,605: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:05:35,656: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:05:35,867: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:05:38,078: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:05:38,296: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:07:45,340: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445174396672, Getting Clients Page...
2021-09-30 17:07:45,379: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445174396672, Page list of 'Clients'.
2021-09-30 17:07:45,725: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:07:50,952: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:07:51,229: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445174396672, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:09:27,355: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445174396672, Page list of 'Adversaires'.
2021-09-30 17:09:27,811: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:09:59,079: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445086639872, Page list of 'Adversaires'.
2021-09-30 17:09:59,367: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:10:41,467: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7184, 140445086639872, Getting Clients Page...
2021-09-30 17:10:41,525: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7184, 140445086639872, Page list of 'Clients'.
2021-09-30 17:10:41,833: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:10:43,405: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445086639872, Page list of 'Adversaires'.
2021-09-30 17:10:43,609: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:11:58,353: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7184, 140445086639872, Page list of 'Adversaires'.
2021-09-30 17:11:58,530: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /adversaires/page/1/city/all/search/all-list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py", line 114, in justice_adversaires
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:15,155: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:12:19,877: ERROR [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7184, 140445086639872, Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Projects/Python_Projects/justice_law_office_django/justice/views.py", line 13, in index
    return render(request=request, template_name=template_name, context=context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'justice_avocats_adversaires_all' not found. 'justice_avocats_adversaires_all' is not a valid view function or pattern name.
2021-09-30 17:13:06,612: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7184, 140445291833152, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:13:08,086: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7452, 140600297944896, Watching for file changes with StatReloader
2021-09-30 17:15:23,544: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7452, 140600297944896, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:15:25,023: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7475, 140395797497664, Watching for file changes with StatReloader
2021-09-30 17:15:44,194: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7475, 140395797497664, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:15:46,213: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7481, 140513302570816, Watching for file changes with StatReloader
2021-09-30 17:15:58,781: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7490, 140625018701632, Watching for file changes with StatReloader
2021-09-30 17:16:59,937: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7490, 140625018701632, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:17:01,344: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7511, 140654349592384, Watching for file changes with StatReloader
2021-09-30 17:17:03,963: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7511, 140654349592384, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:17:05,882: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7518, 140267970496320, Watching for file changes with StatReloader
2021-09-30 17:17:16,116: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7518, 140267970496320, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 17:17:17,635: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7525, 139746806351680, Watching for file changes with StatReloader
2021-09-30 17:17:29,168: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7525, 139746806351680, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/urls.py changed, reloading.
2021-09-30 17:17:30,892: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7534, 140348908578624, Watching for file changes with StatReloader
2021-09-30 17:17:32,292: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348673120000, Not Found: /dist/images/profile-9.jpg
2021-09-30 17:17:32,380: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/profile-2.jpg
2021-09-30 17:17:32,398: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/profile-12.jpg
2021-09-30 17:17:32,575: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-5.jpg
2021-09-30 17:17:32,581: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/profile-11.jpg
2021-09-30 17:17:32,590: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-2.jpg
2021-09-30 17:17:32,679: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-1.jpg
2021-09-30 17:17:32,762: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-9.jpg
2021-09-30 17:17:32,782: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/profile-6.jpg
2021-09-30 17:17:32,762: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/preview-15.jpg
2021-09-30 17:17:32,874: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/preview-11.jpg
2021-09-30 17:17:33,065: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/profile-14.jpg
2021-09-30 17:17:33,075: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /dist/images/preview-13.jpg
2021-09-30 17:17:33,084: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/preview-8.jpg
2021-09-30 17:17:33,365: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348689905408, Not Found: /dist/images/preview-3.jpg
2021-09-30 17:17:33,450: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348715083520, Not Found: /dist/images/preview-12.jpg
2021-09-30 17:17:33,643: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348698298112, Not Found: /dist/images/profile-3.jpg
2021-09-30 17:17:33,809: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/images/profile-4.jpg
2021-09-30 17:17:34,565: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /dist/json/location.json
2021-09-30 17:17:34,773: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7534, 140348706690816, Page list of 'Adversaires'.
2021-09-30 17:17:35,006: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:17:52,962: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7534, 140348706690816, Page list of 'Adversaires'.
2021-09-30 17:17:53,223: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348706690816, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:18:10,439: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7534, 140348706690816, Page list of 'Adversaires'.
2021-09-30 17:18:11,111: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:19:43,945: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7534, 140348681512704, Getting Clients Page...
2021-09-30 17:19:43,979: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7534, 140348681512704, Page list of 'Clients'.
2021-09-30 17:19:44,272: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:19:49,494: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:113], adversaires.views, views, 7534, 140348681512704, Page list of 'Adversaires'.
2021-09-30 17:19:49,710: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7534, 140348681512704, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:20:22,955: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: trigger_reload:217], django.utils.autoreload, autoreload, 7534, 140348908578624, /home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py changed, reloading.
2021-09-30 17:20:24,374: INFO [/usr/lib/python3/dist-packages/django/utils/autoreload.py: run_with_reloader:597], django.utils.autoreload, autoreload, 7642, 140666306185024, Watching for file changes with StatReloader
2021-09-30 17:20:28,230: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:111], adversaires.views, views, 7642, 140666188486400, Page list of 'Adversaires'.
2021-09-30 17:20:28,584: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:22:55,242: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:111], adversaires.views, views, 7642, 140666188486400, Page list of 'Adversaires'.
2021-09-30 17:22:55,504: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:22:59,614: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: adversaire_form:173], adversaires.views, views, 7642, 140666188486400, Page Creating of 'Adversaire'
2021-09-30 17:22:59,946: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/1/dist/images/profile-9.jpg
2021-09-30 17:23:18,005: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: adversaire_form:161], adversaires.views, views, 7642, 140666188486400, 'BOULAMIN Ahmed' Adversaire has been Updated.
2021-09-30 17:23:18,115: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:111], adversaires.views, views, 7642, 140666188486400, Page list of 'Adversaires'.
2021-09-30 17:23:18,514: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:23:57,240: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/adversaires/views.py: justice_adversaires:111], adversaires.views, views, 7642, 140666188486400, Page list of 'Adversaires'.
2021-09-30 17:23:57,531: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /adversaires/page/1/city/all/search/dist/images/profile-9.jpg
2021-09-30 17:24:04,135: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients_all:45], clients.views, views, 7642, 140666188486400, Getting Clients Page...
2021-09-30 17:24:04,203: INFO [/home/kali/Projects/Python_Projects/justice_law_office_django/clients/views.py: justice_clients:113], clients.views, views, 7642, 140666188486400, Page list of 'Clients'.
2021-09-30 17:24:04,424: WARNING [/usr/lib/python3/dist-packages/django/utils/log.py: log_response:222], django.request, log, 7642, 140666188486400, Not Found: /clients/page/1/city/all/search/dist/images/profile-9.jpg
